on:
  push:

name: Secret Leaks

jobs:
  trufflehog:
    # TODO: xethub-poc: undo when poc complete
    # runs-on: ubuntu-latest
    runs-on:
      group: cpu-low
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
